project_id = "ajxslqtyzxcvtmneiagw"

[functions.send-notification]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-waste-scanner]
verify_jwt = false
